// Service statique pour données phonémiques immuables (IPA, rareté, etc.)
// Utilisation : PhonemeDataService.getIPA(PhonemeType.VoicedBilabialNasal)
//              PhonemeDataService.getRarity(PhonemeType.VoicedBilabialNasal)

import { PhonemeType } from "../types";

export class PhonemeDataService {
  private static readonly phonemeToIPA: Partial<Record<PhonemeType, string>> = {
    [PhonemeType.VoicedBilabialNasal]: "m",
    [PhonemeType.VoicedLabiodentalNasal]: "ɱ",
    [PhonemeType.VoicedAlveolarNasal]: "n",
    [PhonemeType.VoicedRetroflexNasal]: "ɳ",
    [PhonemeType.VoicedPalatalNasal]: "ɲ",
    [PhonemeType.VoicedVelarNasal]: "ŋ",
    [PhonemeType.VoicedUvularNasal]: "ɴ",
    [PhonemeType.VoicelessBilabialPlosive]: "p",
    [PhonemeType.VoicedBilabialPlosive]: "b",
    [PhonemeType.VoicelessAlveolarPlosive]: "t",
    [PhonemeType.VoicedAlveolarPlosive]: "d",
    [PhonemeType.VoicelessRetroflexPlosive]: "ʈ",
    [PhonemeType.VoicedRetroflexPlosive]: "ɖ",
    [PhonemeType.VoicelessPalatalPlosive]: "c",
    [PhonemeType.VoicedPalatalPlosive]: "ɟ",
    [PhonemeType.VoicelessVelarPlosive]: "k",
    [PhonemeType.VoicedVelarPlosive]: "ɡ",
    [PhonemeType.VoicelessUvularPlosive]: "q",
    [PhonemeType.VoicedUvularPlosive]: "ɢ",
    [PhonemeType.VoicelessGlottalPlosive]: "ʔ",
    [PhonemeType.VoicelessBilabialFricative]: "ɸ",
    [PhonemeType.VoicedBilabialFricative]: "β",
    [PhonemeType.VoicelessLabiodentalFricative]: "f",
    [PhonemeType.VoicedLabiodentalFricative]: "v",
    [PhonemeType.VoicelessDentalFricative]: "θ",
    [PhonemeType.VoicedDentalFricative]: "ð",
    [PhonemeType.VoicelessAlveolarFricative]: "s",
    [PhonemeType.VoicedAlveolarFricative]: "z",
    [PhonemeType.VoicelessPostalveolarFricative]: "ʃ",
    [PhonemeType.VoicedPostalveolarFricative]: "ʒ",
    [PhonemeType.VoicelessRetroflexFricative]: "ʂ",
    [PhonemeType.VoicedRetroflexFricative]: "ʐ",
    [PhonemeType.VoicelessPalatalFricative]: "ç",
    [PhonemeType.VoicedPalatalFricative]: "ʝ",
    [PhonemeType.VoicelessVelarFricative]: "x",
    [PhonemeType.VoicedVelarFricative]: "ɣ",
    [PhonemeType.VoicelessUvularFricative]: "χ",
    [PhonemeType.VoicedUvularFricative]: "ʁ",
    [PhonemeType.VoicelessPharyngealFricative]: "ħ",
    [PhonemeType.VoicedPharyngealFricative]: "ʕ",
    [PhonemeType.VoicelessGlottalFricative]: "h",
    [PhonemeType.VoicedGlottalFricative]: "ɦ",
    [PhonemeType.VoicedLabioDentalApproximant]: "ʋ",
    [PhonemeType.VoicedAlveolarApproximant]: "ɹ",
    [PhonemeType.VoicedRetroflexApproximant]: "ɻ",
    [PhonemeType.VoicedPalatalApproximant]: "j",
    [PhonemeType.VoicedLabioVelarApproximant]: "w",
    [PhonemeType.VoicedVelarApproximant]: "ɰ",
    [PhonemeType.VoicedBilabialTrill]: "ʙ",
    [PhonemeType.VoicedAlveolarTrill]: "r",
    [PhonemeType.VoicedUvularTrill]: "ʀ",
    [PhonemeType.Voicedlabiodentalflap]: "ⱱ",
    [PhonemeType.VoicedAlveolarTap]: "ɾ",
    [PhonemeType.VoicedRetroflexTap]: "ɽ",
    [PhonemeType.VoicelessAlveolarLateralFricative]: "ɬ",
    [PhonemeType.VoicedAlveolarLateralFricative]: "ɮ",
    [PhonemeType.VoicedAlveolarLateralApproximant]: "l",
    [PhonemeType.VoicedRetroflexLateralApproximant]: "ɭ",
    [PhonemeType.VoicedPalatalLateralApproximant]: "ʎ",
    [PhonemeType.VoicedVelarLateralApproximant]: "ʟ",
    [PhonemeType.CloseFrontUnrounded]: "i",
    [PhonemeType.CloseFrontRounded]: "y",
    [PhonemeType.CloseCentralUnrounded]: "ɨ",
    [PhonemeType.CloseCentralRounded]: "ʉ",
    [PhonemeType.CloseBackUnrounded]: "ɯ",
    [PhonemeType.CloseBackRounded]: "u",
    [PhonemeType.NearCloseFrontUnrounded]: "ɪ",
    [PhonemeType.NearCloseFrontRounded]: "ʏ",
    [PhonemeType.NearCloseBackRounded]: "ʊ",
    [PhonemeType.CloseMidFrontUnrounded]: "e",
    [PhonemeType.CloseMidFrontRounded]: "ø",
    [PhonemeType.MidCentral]: "ə",
    [PhonemeType.OpenMidFrontUnrounded]: "ɛ",
    [PhonemeType.OpenMidFrontRounded]: "œ",
    [PhonemeType.OpenMidBackUnrounded]: "ʌ",
    [PhonemeType.OpenMidBackRounded]: "ɔ",
    [PhonemeType.NearOpenFrontUnrounded]: "æ",
    [PhonemeType.OpenFrontUnrounded]: "a",
    [PhonemeType.OpenBackUnrounded]: "ɑ",
    [PhonemeType.OpenBackRounded]: "ɒ"
  };

  private static readonly phonemeToRarity: Partial<Record<PhonemeType, number>> = {
    [PhonemeType.VoicedBilabialNasal]: 1,
    [PhonemeType.VoicedLabiodentalNasal]: 3,
    [PhonemeType.VoicedAlveolarNasal]: 1,
    [PhonemeType.VoicedRetroflexNasal]: 4,
    [PhonemeType.VoicedPalatalNasal]: 3,
    [PhonemeType.VoicedVelarNasal]: 2,
    [PhonemeType.VoicedUvularNasal]: 5,
    [PhonemeType.VoicelessBilabialPlosive]: 1,
    [PhonemeType.VoicedBilabialPlosive]: 1,
    [PhonemeType.VoicelessAlveolarPlosive]: 1,
    [PhonemeType.VoicedAlveolarPlosive]: 1,
    [PhonemeType.VoicelessRetroflexPlosive]: 4,
    [PhonemeType.VoicedRetroflexPlosive]: 4,
    [PhonemeType.VoicelessPalatalPlosive]: 5,
    [PhonemeType.VoicedPalatalPlosive]: 5,
    [PhonemeType.VoicelessVelarPlosive]: 1,
    [PhonemeType.VoicedVelarPlosive]: 1,
    [PhonemeType.VoicelessUvularPlosive]: 5,
    [PhonemeType.VoicedUvularPlosive]: 5,
    [PhonemeType.VoicelessGlottalPlosive]: 3,
    [PhonemeType.VoicelessBilabialFricative]: 4,
    [PhonemeType.VoicedBilabialFricative]: 4,
    [PhonemeType.VoicelessLabiodentalFricative]: 1,
    [PhonemeType.VoicedLabiodentalFricative]: 1,
    [PhonemeType.VoicelessDentalFricative]: 2,
    [PhonemeType.VoicedDentalFricative]: 2,
    [PhonemeType.VoicelessAlveolarFricative]: 1,
    [PhonemeType.VoicedAlveolarFricative]: 1,
    [PhonemeType.VoicelessPostalveolarFricative]: 2,
    [PhonemeType.VoicedPostalveolarFricative]: 2,
    [PhonemeType.VoicelessRetroflexFricative]: 4,
    [PhonemeType.VoicedRetroflexFricative]: 4,
    [PhonemeType.VoicelessPalatalFricative]: 4,
    [PhonemeType.VoicedPalatalFricative]: 4,
    [PhonemeType.VoicelessVelarFricative]: 2,
    [PhonemeType.VoicedVelarFricative]: 2,
    [PhonemeType.VoicelessUvularFricative]: 4,
    [PhonemeType.VoicedUvularFricative]: 4,
    [PhonemeType.VoicelessPharyngealFricative]: 5,
    [PhonemeType.VoicedPharyngealFricative]: 5,
    [PhonemeType.VoicelessGlottalFricative]: 1,
    [PhonemeType.VoicedGlottalFricative]: 3,
    [PhonemeType.VoicedLabioDentalApproximant]: 3,
    [PhonemeType.VoicedAlveolarApproximant]: 2,
    [PhonemeType.VoicedRetroflexApproximant]: 4,
    [PhonemeType.VoicedPalatalApproximant]: 1,
    [PhonemeType.VoicedLabioVelarApproximant]: 1,
    [PhonemeType.VoicedVelarApproximant]: 4,
    [PhonemeType.VoicedBilabialTrill]: 5,
    [PhonemeType.VoicedAlveolarTrill]: 2,
    [PhonemeType.VoicedUvularTrill]: 4,
    [PhonemeType.Voicedlabiodentalflap]: 5,
    [PhonemeType.VoicedAlveolarTap]: 2,
    [PhonemeType.VoicedRetroflexTap]: 5,
    [PhonemeType.VoicelessAlveolarLateralFricative]: 5,
    [PhonemeType.VoicedAlveolarLateralFricative]: 5,
    [PhonemeType.VoicedAlveolarLateralApproximant]: 1,
    [PhonemeType.VoicedRetroflexLateralApproximant]: 4,
    [PhonemeType.VoicedPalatalLateralApproximant]: 5,
    [PhonemeType.VoicedVelarLateralApproximant]: 5,
    [PhonemeType.CloseFrontUnrounded]: 1,
    [PhonemeType.CloseFrontRounded]: 2,
    [PhonemeType.CloseCentralUnrounded]: 4,
    [PhonemeType.CloseCentralRounded]: 5,
    [PhonemeType.CloseBackUnrounded]: 4,
    [PhonemeType.CloseBackRounded]: 1,
    [PhonemeType.NearCloseFrontUnrounded]: 1,
    [PhonemeType.NearCloseFrontRounded]: 3,
    [PhonemeType.NearCloseBackRounded]: 2,
    [PhonemeType.CloseMidFrontUnrounded]: 1,
    [PhonemeType.CloseMidFrontRounded]: 2,
    [PhonemeType.MidCentral]: 1,
    [PhonemeType.OpenMidFrontUnrounded]: 2,
    [PhonemeType.OpenMidFrontRounded]: 3,
    [PhonemeType.OpenMidBackUnrounded]: 3,
    [PhonemeType.OpenMidBackRounded]: 2,
    [PhonemeType.NearOpenFrontUnrounded]: 2,
    [PhonemeType.OpenFrontUnrounded]: 1,
    [PhonemeType.OpenBackUnrounded]: 1,
    [PhonemeType.OpenBackRounded]: 3
  };

  static getIPA(phoneme: PhonemeType): string | undefined {
    return this.phonemeToIPA[phoneme];
  }

  static getRarity(phoneme: PhonemeType): number | undefined {
    return this.phonemeToRarity[phoneme];
  }
}
