// Inspiré de PhonemeCategories.cs
// Listes de phonèmes pour React/TypeScript

export type Phoneme = string;

// Enum complet des phonèmes (repris de Phoneme.cs)
export const Phonemes = {
  // Consonants
  VoicedBilabialNasal: "VoicedBilabialNasal",
  VoicedLabiodentalNasal: "VoicedLabiodentalNasal",
  VoicedAlveolarNasal: "VoicedAlveolarNasal",
  VoicedRetroflexNasal: "VoicedRetroflexNasal",
  VoicedPalatalNasal: "VoicedPalatalNasal",
  VoicedVelarNasal: "VoicedVelarNasal",
  VoicedUvularNasal: "VoicedUvularNasal",
  VoicelessBilabialPlosive: "VoicelessBilabialPlosive",
  VoicedBilabialPlosive: "VoicedBilabialPlosive",
  VoicelessAlveolarPlosive: "VoicelessAlveolarPlosive",
  VoicedAlveolarPlosive: "VoicedAlveolarPlosive",
  VoicelessRetroflexPlosive: "VoicelessRetroflexPlosive",
  VoicedRetroflexPlosive: "VoicedRetroflexPlosive",
  VoicelessPalatalPlosive: "VoicelessPalatalPlosive",
  VoicedPalatalPlosive: "VoicedPalatalPlosive",
  VoicelessVelarPlosive: "VoicelessVelarPlosive",
  VoicedVelarPlosive: "VoicedVelarPlosive",
  VoicelessUvularPlosive: "VoicelessUvularPlosive",
  VoicedUvularPlosive: "VoicedUvularPlosive",
  GlottalStop: "GlottalStop",
  VoicelessBilabialFricative: "VoicelessBilabialFricative",
  VoicedBilabialFricative: "VoicedBilabialFricative",
  VoicelessLabiodentalFricative: "VoicelessLabiodentalFricative",
  VoicedLabiodentalFricative: "VoicedLabiodentalFricative",
  VoicelessDentalFricative: "VoicelessDentalFricative",
  VoicedDentalFricative: "VoicedDentalFricative",
  VoicelessAlveolarFricative: "VoicelessAlveolarFricative",
  VoicedAlveolarFricative: "VoicedAlveolarFricative",
  VoicelessPostalveolarFricative: "VoicelessPostalveolarFricative",
  VoicedPostalveolarFricative: "VoicedPostalveolarFricative",
  VoicelessRetroflexFricative: "VoicelessRetroflexFricative",
  VoicedRetroflexFricative: "VoicedRetroflexFricative",
  VoicelessPalatalFricative: "VoicelessPalatalFricative",
  VoicedPalatalFricative: "VoicedPalatalFricative",
  VoicelessVelarFricative: "VoicelessVelarFricative",
  VoicedVelarFricative: "VoicedVelarFricative",
  VoicelessUvularFricative: "VoicelessUvularFricative",
  VoicedUvularFricative: "VoicedUvularFricative",
  VoicelessPharyngealFricative: "VoicelessPharyngealFricative",
  VoicedPharyngealFricative: "VoicedPharyngealFricative",
  VoicelessGlottalFricative: "VoicelessGlottalFricative",
  VoicedGlottalFricative: "VoicedGlottalFricative",
  LabiodentalApproximant: "LabiodentalApproximant",
  AlveolarApproximant: "AlveolarApproximant",
  RetroflexApproximant: "RetroflexApproximant",
  PalatalApproximant: "PalatalApproximant",
  VelarApproximant: "VelarApproximant",
  BilabialTrill: "BilabialTrill",
  AlveolarTrill: "AlveolarTrill",
  UvularTrill: "UvularTrill",
  AlveolarTap: "AlveolarTap",
  RetroflexTap: "RetroflexTap",
  VoicelessAlveolarLateralFricative: "VoicelessAlveolarLateralFricative",
  VoicedAlveolarLateralFricative: "VoicedAlveolarLateralFricative",
  AlveolarLateralApproximant: "AlveolarLateralApproximant",
  RetroflexLateralApproximant: "RetroflexLateralApproximant",
  PalatalLateralApproximant: "PalatalLateralApproximant",
  VelarLateralApproximant: "VelarLateralApproximant",
  // Vowels (première série)
  CloseFrontUnroundedVowel: "CloseFrontUnroundedVowel",
  CloseFrontRoundedVowel: "CloseFrontRoundedVowel",
  CloseCentralUnroundedVowel: "CloseCentralUnroundedVowel",
  CloseCentralRoundedVowel: "CloseCentralRoundedVowel",
  CloseBackUnroundedVowel: "CloseBackUnroundedVowel",
  CloseBackRoundedVowel: "CloseBackRoundedVowel",
  NearCloseNearFrontUnroundedVowel: "NearCloseNearFrontUnroundedVowel",
  NearCloseNearFrontRoundedVowel: "NearCloseNearFrontRoundedVowel",
  NearCloseNearBackRoundedVowel: "NearCloseNearBackRoundedVowel",
  CloseMidFrontUnroundedVowel: "CloseMidFrontUnroundedVowel",
  CloseMidFrontRoundedVowel: "CloseMidFrontRoundedVowel",
  MidCentralVowel: "MidCentralVowel",
  OpenMidFrontUnroundedVowel: "OpenMidFrontUnroundedVowel",
  OpenMidFrontRoundedVowel: "OpenMidFrontRoundedVowel",
  OpenMidBackUnroundedVowel: "OpenMidBackUnroundedVowel",
  OpenMidBackRoundedVowel: "OpenMidBackRoundedVowel",
  NearOpenFrontUnroundedVowel: "NearOpenFrontUnroundedVowel",
  OpenFrontUnroundedVowel: "OpenFrontUnroundedVowel",
  OpenBackUnroundedVowel: "OpenBackUnroundedVowel",
  OpenBackRoundedVowel: "OpenBackRoundedVowel",
  // Vowels (deuxième série)
  CloseFrontUnrounded: "CloseFrontUnrounded",
  CloseFrontRounded: "CloseFrontRounded",
  CloseCentralUnrounded: "CloseCentralUnrounded",
  CloseCentralRounded: "CloseCentralRounded",
  CloseBackUnrounded: "CloseBackUnrounded",
  CloseBackRounded: "CloseBackRounded",
  NearCloseFrontUnrounded: "NearCloseFrontUnrounded",
  NearCloseFrontRounded: "NearCloseFrontRounded",
  NearCloseBackRounded: "NearCloseBackRounded",
  CloseMidFrontUnrounded: "CloseMidFrontUnrounded",
  CloseMidFrontRounded: "CloseMidFrontRounded",
  CloseMidCentralUnrounded: "CloseMidCentralUnrounded",
  CloseMidCentralRounded: "CloseMidCentralRounded",
  CloseMidBackUnrounded: "CloseMidBackUnrounded",
  CloseMidBackRounded: "CloseMidBackRounded",
  MidCentral: "MidCentral",
  OpenMidFrontUnrounded: "OpenMidFrontUnrounded",
  OpenMidFrontRounded: "OpenMidFrontRounded",
  OpenMidCentralUnrounded: "OpenMidCentralUnrounded",
  OpenMidCentralRounded: "OpenMidCentralRounded",
  OpenMidBackUnrounded: "OpenMidBackUnrounded",
  OpenMidBackRounded: "OpenMidBackRounded",
  NearOpenFrontUnrounded: "NearOpenFrontUnrounded",
  NearOpenCentral: "NearOpenCentral",
  OpenFrontUnrounded: "OpenFrontUnrounded",
  OpenFrontRounded: "OpenFrontRounded",
  OpenBackUnrounded: "OpenBackUnrounded",
  OpenBackRounded: "OpenBackRounded",
  VoicedAlveolarLateralApproximant: "VoicedAlveolarLateralApproximant",
  VoicedRetroflexLateralApproximant: "VoicedRetroflexLateralApproximant",
  VoicedLabioDentalApproximant: "VoicedLabioDentalApproximant",
  VoicedAlveolarApproximant: "VoicedAlveolarApproximant",
  VoicedRetroflexApproximant: "VoicedRetroflexApproximant",
  VoicedPalatalApproximant: "VoicedPalatalApproximant",
  VoicedVelarApproximant: "VoicedVelarApproximant",
  VoicedBilabialTrill: "VoicedBilabialTrill",
  VoicedAlveolarTrill: "VoicedAlveolarTrill",
  VoicedUvularTrill: "VoicedUvularTrill",
  VoicedAlveolarTap: "VoicedAlveolarTap",
  VoicedRetroflexTap: "VoicedRetroflexTap",
  VoicedPalatalLateralApproximant: "VoicedPalatalLateralApproximant",
  VoicedVelarLateralApproximant: "VoicedVelarLateralApproximant",
  VoicedPostAlveolarSibilantFricative: "VoicedPostAlveolarSibilantFricative",
  VoicelessPostAlveolarSibilantFricative: "VoicelessPostAlveolarSibilantFricative",
  VoicedLabioDentalFricative: "VoicedLabioDentalFricative",
  VoicelessLabioDentalFricative: "VoicelessLabioDentalFricative",
  VoicelessGlottalPlosive: "VoicelessGlottalPlosive",
  VoicedLabioDentalNasal: "VoicedLabioDentalNasal",
  Voicedlabiodentalflap: "Voicedlabiodentalflap",
  VoicedLabioVelarApproximant: "VoicedLabioVelarApproximant",
};

// Catégories de voyelles (height/rows)
export const close = [
  Phonemes.CloseFrontUnrounded,
  Phonemes.CloseFrontRounded,
  Phonemes.CloseCentralUnrounded,
  Phonemes.CloseCentralRounded,
  Phonemes.CloseBackUnrounded,
  Phonemes.CloseBackRounded,
];
export const nearClose = [
  Phonemes.NearCloseFrontUnrounded,
  Phonemes.NearCloseFrontRounded,
  Phonemes.NearCloseBackRounded,
];
export const closeMid = [
  Phonemes.CloseMidFrontUnrounded,
  Phonemes.CloseMidFrontRounded,
  Phonemes.CloseMidCentralUnrounded,
  Phonemes.CloseMidCentralRounded,
  Phonemes.CloseMidBackUnrounded,
  Phonemes.CloseMidBackRounded,
];
export const mid = [Phonemes.MidCentral];
export const openMid = [
  Phonemes.OpenMidFrontUnrounded,
  Phonemes.OpenMidFrontRounded,
  Phonemes.OpenMidCentralUnrounded,
  Phonemes.OpenMidCentralRounded,
  Phonemes.OpenMidBackUnrounded,
  Phonemes.OpenMidBackRounded,
];
export const nearOpen = [
  Phonemes.NearOpenFrontUnrounded,
  Phonemes.NearOpenCentral,
];
export const open = [
  Phonemes.OpenFrontUnrounded,
  Phonemes.OpenFrontRounded,
  Phonemes.OpenBackUnrounded,
  Phonemes.OpenBackRounded,
];
export const vowels = [
  ...close,
  ...nearClose,
  ...closeMid,
  ...mid,
  ...openMid,
  ...nearOpen,
  ...open,
];
// Catégories de voyelles (backness/columns)
export const front = [
  Phonemes.CloseFrontUnrounded,
  Phonemes.CloseFrontRounded,
  Phonemes.NearCloseFrontUnrounded,
  Phonemes.NearCloseFrontRounded,
  Phonemes.CloseMidFrontUnrounded,
  Phonemes.CloseMidFrontRounded,
  Phonemes.OpenMidFrontUnrounded,
  Phonemes.OpenMidFrontRounded,
  Phonemes.NearOpenFrontUnrounded,
  Phonemes.OpenFrontUnrounded,
  Phonemes.OpenFrontRounded,
];
export const central = [
  Phonemes.CloseCentralUnrounded,
  Phonemes.CloseCentralRounded,
  Phonemes.CloseMidCentralUnrounded,
  Phonemes.CloseMidCentralRounded,
  Phonemes.MidCentral,
  Phonemes.OpenMidCentralUnrounded,
  Phonemes.OpenMidCentralRounded,
  Phonemes.NearOpenCentral,
];
export const back = [
  Phonemes.CloseBackUnrounded,
  Phonemes.CloseBackRounded,
  Phonemes.NearCloseBackRounded,
  Phonemes.CloseMidBackUnrounded,
  Phonemes.CloseMidBackRounded,
  Phonemes.OpenMidBackUnrounded,
  Phonemes.OpenMidBackRounded,
  Phonemes.OpenBackUnrounded,
  Phonemes.OpenBackRounded,
];
// Roundness
export const rounded = [
  Phonemes.CloseFrontRounded,
  Phonemes.CloseCentralRounded,
  Phonemes.CloseBackRounded,
  Phonemes.NearCloseFrontRounded,
  Phonemes.CloseMidFrontRounded,
  Phonemes.CloseMidCentralRounded,
  Phonemes.CloseMidBackRounded,
  Phonemes.OpenMidFrontRounded,
  Phonemes.OpenMidCentralRounded,
  Phonemes.OpenMidBackRounded,
  Phonemes.NearOpenFrontUnrounded,
  Phonemes.OpenFrontRounded,
  Phonemes.OpenBackRounded,
];
export const unrounded = [
  Phonemes.CloseFrontUnrounded,
  Phonemes.CloseCentralUnrounded,
  Phonemes.CloseBackUnrounded,
  Phonemes.NearCloseFrontUnrounded,
  Phonemes.CloseMidFrontUnrounded,
  Phonemes.CloseMidCentralUnrounded,
  Phonemes.CloseMidBackUnrounded,
  Phonemes.OpenMidFrontUnrounded,
  Phonemes.OpenMidCentralUnrounded,
  Phonemes.OpenMidBackUnrounded,
  Phonemes.NearOpenFrontUnrounded,
  Phonemes.OpenFrontUnrounded,
  Phonemes.OpenBackUnrounded,
];
// Consonant places
export const bilabial = [
  Phonemes.VoicelessBilabialPlosive,
  Phonemes.VoicedBilabialPlosive,
  Phonemes.VoicedBilabialNasal,
  Phonemes.VoicelessBilabialFricative,
  Phonemes.VoicedBilabialFricative,
  Phonemes.BilabialTrill,
];
export const labiodental = [
  Phonemes.VoicelessLabiodentalFricative,
  Phonemes.VoicedLabiodentalFricative,
  Phonemes.VoicedLabioDentalApproximant,
];
export const dental = [
  Phonemes.VoicelessDentalFricative,
  Phonemes.VoicedDentalFricative,
];
export const alveolar = [
  Phonemes.VoicelessAlveolarPlosive,
  Phonemes.VoicedAlveolarPlosive,
  Phonemes.VoicedAlveolarNasal,
  Phonemes.VoicelessAlveolarFricative,
  Phonemes.VoicedAlveolarFricative,
  Phonemes.VoicedAlveolarApproximant,
  Phonemes.AlveolarTrill,
  Phonemes.AlveolarTap,
  Phonemes.VoicelessAlveolarLateralFricative,
  Phonemes.VoicedAlveolarLateralFricative,
  Phonemes.AlveolarLateralApproximant,
];
export const postalveolar = [
  Phonemes.VoicelessPostalveolarFricative,
  Phonemes.VoicedPostalveolarFricative,
];
export const retroflex = [
  Phonemes.VoicelessRetroflexPlosive,
  Phonemes.VoicedRetroflexPlosive,
  Phonemes.VoicelessRetroflexFricative,
  Phonemes.VoicedRetroflexFricative,
  Phonemes.RetroflexApproximant,
  Phonemes.RetroflexTap,
  Phonemes.RetroflexLateralApproximant,
  Phonemes.VoicedRetroflexNasal,
];
export const palatal = [
  Phonemes.VoicedPalatalNasal,
  Phonemes.VoicelessPalatalPlosive,
  Phonemes.VoicedPalatalPlosive,
  Phonemes.VoicelessPalatalFricative,
  Phonemes.VoicedPalatalFricative,
  Phonemes.PalatalApproximant,
  Phonemes.PalatalLateralApproximant,
];
export const velar = [
  Phonemes.VoicelessVelarPlosive,
  Phonemes.VoicedVelarPlosive,
  Phonemes.VoicedVelarNasal,
  Phonemes.VoicelessVelarFricative,
  Phonemes.VoicedVelarFricative,
  Phonemes.VelarApproximant,
  Phonemes.VelarLateralApproximant,
];
export const uvular = [
  Phonemes.VoicelessUvularPlosive,
  Phonemes.VoicedUvularPlosive,
  Phonemes.VoicedUvularNasal,
  Phonemes.VoicelessUvularFricative,
  Phonemes.VoicedUvularFricative,
  Phonemes.UvularTrill,
];
export const pharyngeal = [
  Phonemes.VoicelessPharyngealFricative,
  Phonemes.VoicedPharyngealFricative,
];
export const glottal = [
  Phonemes.VoicelessGlottalPlosive,
  Phonemes.VoicelessGlottalFricative,
  Phonemes.VoicedGlottalFricative,
];
// Manner of articulation
export const plosive = [
  Phonemes.VoicelessBilabialPlosive,
  Phonemes.VoicedBilabialPlosive,
  Phonemes.VoicelessAlveolarPlosive,
  Phonemes.VoicedAlveolarPlosive,
  Phonemes.VoicelessRetroflexPlosive,
  Phonemes.VoicedRetroflexPlosive,
  Phonemes.VoicelessPalatalPlosive,
  Phonemes.VoicedPalatalPlosive,
  Phonemes.VoicelessVelarPlosive,
  Phonemes.VoicedVelarPlosive,
  Phonemes.VoicelessUvularPlosive,
  Phonemes.VoicedUvularPlosive,
  Phonemes.VoicelessGlottalPlosive,
];
export const nasals = [
  Phonemes.VoicedBilabialNasal,
  Phonemes.VoicedLabiodentalNasal,
  Phonemes.VoicedPalatalNasal,
  Phonemes.VoicedAlveolarNasal,
  Phonemes.VoicedVelarNasal,
  Phonemes.VoicedUvularNasal,
  Phonemes.VoicedRetroflexNasal,
];
export const trill = [
  Phonemes.BilabialTrill,
  Phonemes.AlveolarTrill,
  Phonemes.UvularTrill,
];
export const tapOrFlap = [
  Phonemes.Voicedlabiodentalflap,
  Phonemes.AlveolarTap,
  Phonemes.RetroflexTap,
];
export const fricative = [
  Phonemes.VoicelessBilabialFricative,
  Phonemes.VoicedBilabialFricative,
  Phonemes.VoicelessLabiodentalFricative,
  Phonemes.VoicedLabiodentalFricative,
  Phonemes.VoicelessDentalFricative,
  Phonemes.VoicedDentalFricative,
  Phonemes.VoicelessAlveolarFricative,
  Phonemes.VoicedAlveolarFricative,
  Phonemes.VoicelessPostalveolarFricative,
  Phonemes.VoicedPostalveolarFricative,
  Phonemes.VoicelessRetroflexFricative,
  Phonemes.VoicedRetroflexFricative,
  Phonemes.VoicelessPalatalFricative,
  Phonemes.VoicedPalatalFricative,
  Phonemes.VoicelessVelarFricative,
  Phonemes.VoicedVelarFricative,
  Phonemes.VoicelessUvularFricative,
  Phonemes.VoicedUvularFricative,
  Phonemes.VoicelessPharyngealFricative,
  Phonemes.VoicedPharyngealFricative,
  Phonemes.VoicelessGlottalFricative,
  Phonemes.VoicedGlottalFricative,
];
export const lateralFricative = [
  Phonemes.VoicelessAlveolarLateralFricative,
  Phonemes.VoicedAlveolarLateralFricative,
];
export const approximant = [
  Phonemes.AlveolarApproximant,
  Phonemes.LabiodentalApproximant,
  Phonemes.RetroflexApproximant,
  Phonemes.PalatalApproximant,
  Phonemes.VelarApproximant,
];
export const lateralApproximant = [
  Phonemes.AlveolarLateralApproximant,
  Phonemes.RetroflexLateralApproximant,
  Phonemes.PalatalLateralApproximant,
  Phonemes.VelarLateralApproximant,
];